##iMPORTANT LIBRARY

In [1]:
import pandas as pd

In [2]:
transaction = pd.read_csv('/content/transactions.csv')

In [3]:
product = pd.read_csv('/content/products.csv')

In [4]:
price_history = pd.read_csv('/content/price_history.csv')

#summary for table : Pandas head() Method – Viewing the First Records

In [5]:
transaction.head()

   order_detail_id  order_id  order_date  pizza_id  quantity
0                1         1  2026-01-01         4         1
1                2         2  2026-01-01         6         1
2                3         2  2026-01-01         2         1
3                4         2  2026-01-01         9         1
4                5         2  2026-01-01        10         1

In [6]:
product.head()

   pizza_id             name  current_price
0         1      BBQ Chicken          20.75
1         2           Cheese          18.50
2         3  Chicken Alfredo          20.75
3         4         Hawaiian          20.50
4         5       Margherita          20.75

In [7]:
price_history.head()

   pizza_id effective_date  price
0         1     2026-01-01  20.75
1         2     2026-01-01  17.95
2         3     2026-01-01  20.75
3         4     2026-01-01  16.50
4         5     2026-01-01  20.25

##Dataset Size

In [8]:
print('dataset 1')
print(transaction.shape)
print('\n dataset 2')
print(product.shape)
print('\n dataset 3')
print(price_history.shape)

dataset 1
(7164, 5)

 dataset 2
(10, 3)

 dataset 3
(22, 3)

##DATA SET STRUCTURE

In [9]:
print('dataset 1')
print(transaction.info())
print('\n dataset 2')
print(product.info())
print('\n dataset 3')
print(price_history.info())

dataset 1
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7164 entries, 0 to 7163
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_detail_id  7164 non-null   int64
 1   order_id         7164 non-null   int64
 2   order_date       7164 non-null   object
 3   pizza_id         7164 non-null   int64
 4   quantity         7164 non-null   int64
dtypes: int64(4), object(1)
memory usage: 280.0+ KB
None

 dataset 2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pizza_id       10 non-null     int64
 1   name           10 non-null     object
 2   current_price  10 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 372.0+ bytes
None

 dataset 3
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pizza_id        22 non-null     int64
 1   effective_date  22 non-null     object
 2   price           22 non-null     float64
dtypes: float64(1), int64(1), object(1)
memory usage: 660.0+ bytes
None

##Column Names

In [10]:
#columns
print('transaction :',transaction.columns)
print('\n product :', product.columns)
print('\n price_history', price_history.columns)

transaction : Index(['order_detail_id', 'order_id', 'order_date', 'pizza_id', 'quantity'], dtype='object')

 product : Index(['pizza_id', 'name', 'current_price'], dtype='object')

 price_history Index(['pizza_id', 'effective_date', 'price'], dtype='object')

#DATA CLEANING

In [11]:
#CHANGE DATATYPE
transaction['order_date']=pd.to_datetime(transaction['order_date'])
print(transaction.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7164 entries, 0 to 7163
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_detail_id  7164 non-null   int64
 1   order_id         7164 non-null   int64
 2   order_date       7164 non-null   datetime64[ns]
 3   pizza_id         7164 non-null   int64
 4   quantity         7164 non-null   int64
dtypes: datetime64[ns](1), int64(4)
memory usage: 280.0 KB
None

In [12]:
price_history['effective_date']=pd.to_datetime(price_history['effective_date'])
print(price_history.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pizza_id        22 non-null     int64
 1   effective_date  22 non-null     datetime64[ns]
 2   price           22 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 660.0 bytes
None

##Sort before merging

In [13]:
#sort transaction by order_date
transaction.sort_values(by='order_date')

      order_detail_id  order_id order_date  pizza_id  quantity
0                   1         1 2026-01-01         4         1
93                 94        43 2026-01-01         8         1
94                 95        44 2026-01-01         5         1
95                 96        45 2026-01-01         2         1
96                 97        45 2026-01-01         4         1
...               ...       ...        ...       ...       ...
7067             7068      3490 2026-02-28         6         1
7066             7067      3490 2026-02-28         1         1
7065             7066      3489 2026-02-28         1         1
7079             7080      3495 2026-02-28         2         1
7163             7164      3530 2026-02-28        10         2

[7164 rows x 5 columns]

In [14]:
price_history.sort_values(by='effective_date')

    pizza_id effective_date  price
0          1     2026-01-01  20.75
1          2     2026-01-01  17.95
2          3     2026-01-01  20.75
3          4     2026-01-01  16.50
4          5     2026-01-01  20.25
5          6     2026-01-01  17.50
6          7     2026-01-01  15.25
7          8     2026-01-01  20.25
8          9     2026-01-01  20.75
9         10     2026-01-01  20.25
11         4     2026-01-19  17.50
10         7     2026-01-19  16.50
12         2     2026-02-02  18.50
13         4     2026-02-02  18.50
14         5     2026-02-02  20.75
15         6     2026-02-02  18.50
16         7     2026-02-02  18.50
17         8     2026-02-02  20.75
18        10     2026-02-02  21.00
19         4     2026-02-16  20.50
20         6     2026-02-16  20.50
21         7     2026-02-16  20.50

##Apply ASOF Merge

In [15]:
result= pd.merge_asof(transaction,price_history,left_on='order_date', right_on='effective_date', by='pizza_id', direction='backward')

In [16]:
result.head()

,order_detail_id,order_id,order_date,pizza_id,quantity,effective_date,price
0,1,1,2026-01-01,4,1,2026-01-01,16.50
1,2,2,2026-01-01,6,1,2026-01-01,17.50
2,3,2,2026-01-01,2,1,2026-01-01,17.95
3,4,2,2026-01-01,9,1,2026-01-01,20.75
4,5,2,2026-01-01,10,1,2026-01-01,20.25

###FIND REVENUE

In [17]:
import numpy as np

In [18]:
#REVENUE
result["revenue"] = result["price"] * result["quantity"]

In [19]:
result.head()

,order_detail_id,order_id,order_date,pizza_id,quantity,effective_date,price,revenue
0,1,1,2026-01-01,4,1,2026-01-01,16.50,16.50
1,2,2,2026-01-01,6,1,2026-01-01,17.50,17.50
2,3,2,2026-01-01,2,1,2026-01-01,17.95,17.95
3,4,2,2026-01-01,9,1,2026-01-01,20.75,20.75
4,5,2,2026-01-01,10,1,2026-01-01,20.25,20.25

##Round Down to Nearest Integer
####TOTAL REVENUE

In [20]:
#total revenue


total_revenue = np.floor(result['revenue'].sum())

print(total_revenue)

161144.0